batch_size: 8192
img_height: 256
img_width: 256
img_num_channels: 3
seed: 1337
out_folder: 'out/muon_nodual'
img_path: 'inputs/cips.png'
mlp_width: 128
train_steps: 2000
val_freq: 100
pre_dual: False
post_dual: False
# optimizer:
#   optimizer: adam
#   lr: 0.1
#   beta1: 0.9
#   beta2: 0.95
#   w_max: 1
#   wd: 0.08
#   spectral_wd: 0
#   schedule: linear

optimizer:
  optimizer: muon
  lr: 0.2
  beta1: 0.9
  beta2: 0.95
  w_max: 6
  wd: 0.0
  schedule: linear
