batch_size: 8192
img_height: 256
img_width: 256
img_num_channels: 3
seed: 1337
out_folder: 'out/linear-simple'
img_path: 'inputs/cips.png'
mlp_width: 128
train_steps: 1
learning_rate: 0.1
val_freq: 100
dualize_gradients: False
